# Generated by Django 5.0.1 on 2024-01-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('mobilenumber', models.IntegerField(blank=True, null=True)),
                ('propertyName', models.CharField(max_length=100)),
            ],
        ),
    

        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertytype', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_sqft', models.IntegerField()),
                ('dwellingplace', models.CharField(max_length=100)),
            ],
        ),
        
    ]
